import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/node_modules/**',
      'fixtures/**',
      'packages/db/src/generated/**',
      // Generated by Next.js on every build and explicitly not to be edited.
      // It uses triple-slash references, which the TS rules reject.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': 'off',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },

  // packages/domain must stay pure: no I/O, no framework, no repo imports.
  // docs/03-architecture.md states this as a rule; this makes it a build error
  // rather than a convention someone remembers.
  {
    files: ['packages/domain/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@mydivelog/*'],
              message:
                'packages/domain must not import other workspace packages. Pass data in instead — see docs/03-architecture.md § Boundaries And Rules.',
            },
            {
              group: ['node:*', 'fs', 'path', 'http', 'crypto'],
              message:
                'packages/domain must stay free of I/O so it tests in milliseconds without a database.',
            },
          ],
        },
      ],
    },
  },

  // Test files may reach for anything.
  {
    files: ['**/*.test.ts', '**/*.test.tsx'],
    rules: { 'no-restricted-imports': 'off' },
  },
);
